"""steps

Revision ID: 291541f8940b
Revises: f6f4489a9da0
Create Date: 2026-02-14 00:02:51.475693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '291541f8940b'
down_revision: Union[str, Sequence[str], None] = 'f6f4489a9da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stage_inventory',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant', sa.String(length=100), nullable=True),
    sa.Column('stage_number', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stage_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stage_inventory_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stage_inventory_stage_number'), ['stage_number'], unique=False)

    with op.batch_alter_table('bom_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage_number', sa.Integer(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bom_lines', schema=None) as batch_op:
        batch_op.drop_column('stage_number')

    with op.batch_alter_table('stage_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stage_inventory_stage_number'))
        batch_op.drop_index(batch_op.f('ix_stage_inventory_product_id'))

    op.drop_table('stage_inventory')
    # ### end Alembic commands ###
