"""jobrate

Revision ID: 2fa342708bf4
Revises: 98c4712fd8b1
Create Date: 2026-02-13 18:26:33.966155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fa342708bf4'
down_revision: Union[str, Sequence[str], None] = '98c4712fd8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_rates',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('operation_code', sa.String(length=50), nullable=False),
    sa.Column('operation_name', sa.String(length=255), nullable=False),
    sa.Column('rate', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sequence', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_rates_operation_code'), ['operation_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_rates_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_rates_product_id'))
        batch_op.drop_index(batch_op.f('ix_job_rates_operation_code'))

    op.drop_table('job_rates')
    # ### end Alembic commands ###
