"""bom

Revision ID: 3ed0f2f99966
Revises: baacce5f3551
Create Date: 2026-02-10 15:33:17.205950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ed0f2f99966'
down_revision: Union[str, Sequence[str], None] = 'baacce5f3551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bom_lines',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('variant', sa.String(length=100), nullable=True),
    sa.Column('batch_qty', sa.Numeric(precision=15, scale=2), server_default='1', nullable=False),
    sa.Column('raw_qty', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bom_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bom_lines_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bom_lines_raw_material_id'), ['raw_material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bom_lines_variant'), ['variant'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bom_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bom_lines_variant'))
        batch_op.drop_index(batch_op.f('ix_bom_lines_raw_material_id'))
        batch_op.drop_index(batch_op.f('ix_bom_lines_product_id'))

    op.drop_table('bom_lines')
    # ### end Alembic commands ###
