"""inventorylog

Revision ID: 98c4712fd8b1
Revises: e83647afa2b1
Create Date: 2026-02-12 21:13:35.133117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c4712fd8b1'
down_revision: Union[str, Sequence[str], None] = 'e83647afa2b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_logs',
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('previous_qty', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('new_qty', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_logs_raw_material_id'), ['raw_material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_logs_raw_material_id'))

    op.drop_table('inventory_logs')
    # ### end Alembic commands ###
