"""products

Revision ID: af9c42b22928
Revises: 70c653f8ed1c
Create Date: 2026-02-10 01:35:26.895898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af9c42b22928'
down_revision: Union[str, Sequence[str], None] = '70c653f8ed1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('group', sa.String(length=255), nullable=True),
    sa.Column('mrp', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('qty', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('gst', sa.String(length=20), nullable=True),
    sa.Column('hsn', sa.String(length=20), nullable=True),
    sa.Column('part_no', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('product_image', sa.String(length=512), nullable=True),
    sa.Column('distributor_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('dealer_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('retail_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'category', name='uq_products_name_category')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_part_no'), ['part_no'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_part_no'))
        batch_op.drop_index(batch_op.f('ix_products_name'))

    op.drop_table('products')
    # ### end Alembic commands ###
