"""products-no-unique

Revision ID: baacce5f3551
Revises: af9c42b22928
Create Date: 2026-02-10 03:28:28.295670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baacce5f3551'
down_revision: Union[str, Sequence[str], None] = 'af9c42b22928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_products_name_category'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_products_name_category'), ['name', 'category'])

    # ### end Alembic commands ###
