"""worklog

Revision ID: d8e740248f83
Revises: 2fa342708bf4
Create Date: 2026-02-13 21:34:52.119265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e740248f83'
down_revision: Union[str, Sequence[str], None] = '2fa342708bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_logs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_rate_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_rate_id'], ['job_rates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_logs_job_rate_id'), ['job_rate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_logs_work_date'), ['work_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_logs_work_date'))
        batch_op.drop_index(batch_op.f('ix_work_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_logs_job_rate_id'))

    op.drop_table('work_logs')
    # ### end Alembic commands ###
