"""raw-enum

Revision ID: e83647afa2b1
Revises: 3ed0f2f99966
Create Date: 2026-02-10 16:24:14.290452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e83647afa2b1'
down_revision: Union[str, Sequence[str], None] = '3ed0f2f99966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_materials', schema=None) as batch_op:
        batch_op.alter_column('unit_type',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_materials', schema=None) as batch_op:
        batch_op.alter_column('unit_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)

    # ### end Alembic commands ###
